#!/bin/bash

#SBATCH --job-name=JTVAE-TRA

#SBATCH --partition=gpu
#V100
#SBATCH --gres=gpu:v100:1
#P100
##SBATCH --gres=gpu:p100:1

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=119:00:00

source /home/blackst/.bashrc
hostname -s

JTVAE_GPU_PATH="/mnt/projects/ATOM/blackst/GMD/JTVAE/GPU-P3"
conda activate JTVAE-GPU-P3
export PYTHONPATH=$JTVAE_GPU_PATH

WRK="/mnt/projects/ATOM/blackst/GMD/LOGP-JTVAE-PAPER/Train"
echo $WRK
cd $WRK

VAE="$JTVAE_GPU_PATH""/fast_molvae/vae_train_gpu.py"
TRA="../Preprocess/zinc-processed-train"
VOC="../Vocabulary/all_vocab.txt"
DIR="MODEL-TRAIN"
OUT="train.out"

python -u $VAE --train $TRA      \
               --vocab $VOC      \
               --save_dir $DIR   \
               --num_workers 8   \
               --mult_gpus False \
                >& $OUT